service: my-first-service

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1

functions:
  hello:
    handler: src/handler.hello
    events:
      - http:
          path: hello
          method: get